### ISSUE TITLE
Error in Phpexcel.php?

### ISSUE THREAD

**Issue by cr-x** [JanBartels/phpexcel_service#1]
Hi,
I think there is an error in Classes\Service\Phpexcel.php:

Line 44
`$libPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('phpexcel_service') . 'Resources/Private/Contributed/';`

should be:
`$libPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('phpexcel_service-master') . 'Resources/Private/Contributed/';`

Thanks,
Reinhard

**Comment by JanBartels** [comment]
No, it's correct as is because the extkey is "phpexcel_service," but not "phpexcel_service-master". The suffix "-master" is appended by github. Please rename your directory.
